---
abstract: 'Tied hash to persistent CHI cache'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-CHI
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tie-CHI
  repository: git://github.com/jonswar/perl-tie-chi.git
version: 0.01
